name: Maven Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
          server-id: "github"

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Install dependencies needed
        run: |
          mvn install:install-file -Dfile=./tntconcept-core/jars_to_install/jta-1.0.1B.jar -DgroupId=javax.transaction -DartifactId=jta -Dversion=1.0.1B -Dpackaging=jar

          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/olap4j-0.9.6.jar -DgroupId=org.olap4j -DartifactId=olap4j -Dversion=0.9.6 -Dpackaging=jar

          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/mondrian-3.0.0.jar -DgroupId=mondrian -DartifactId=mondrian -Dversion=3.0.0 -Dpackaging=jar

          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/wcf-1.7.0.jar -DgroupId=com.tonbeller.wcf -DartifactId=wcf -Dversion=1.7.0 -Dpackaging=jar
          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/jpivot-1.8.0.jar -DgroupId=com.tonbeller.jpivot -DartifactId=jpivot -Dversion=1.8.0 -Dpackaging=jar
          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/tbutils-wcf-1.7.0.jar -DgroupId=com.tonbeller.tbutils -DartifactId=tbutils-wcf -Dversion=1.7.0 -Dpackaging=jar

          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/javacup-0.10k.jar -DgroupId=java_cup -DartifactId=javacup -Dversion=0.10k -Dpackaging=jar

          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/eigenbase-properties-1.0.jar -DgroupId=org.eigenbase.util.property -DartifactId=eigenbase-properties -Dversion=1.0   -Dpackaging=jar
          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/eigenbase-resgen-1.0.jar -DgroupId=org.eigenbase.resgen -DartifactId=eigenbase-resgen -Dversion=1.0 -Dpackaging=jar
          mvn install:install-file -Dfile=./tntconcept-web/jars_to_install/eigenbase-xom-1.0.jar -DgroupId=org.eigenbase.xom -DartifactId=eigenbase-xom -Dversion=1.0 -Dpackaging=jar


      - name: Prepare Maven Release
        run: |
          mvn -B release:prepare
          NEXT_RELEASE=$(grep -r 'scm.tag=' release.properties | sed 's/scm.tag=//')
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
          mvn deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tntconcept-web/target/*.war"
          tag: ${{ env.NEXT_RELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}
